name: Documentation

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'

permissions:
  contents: read

jobs:
  build-doc:
    name: Build the mdBook documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install mdbook
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook@0.5.0

      - name: Build documentation
        run: mdbook build docs

      - name: Upload documentation
        uses: actions/upload-artifact@v7
        with:
          name: documentation
          path: docs/book
